apiVersion: v1
kind: Namespace
metadata:
  name: hackathon-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-api-deployment
  namespace: hackathon
  labels:
    app: hackathon-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hackathon-api
  template:
    metadata:
      labels:
        app: hackathon-api
    spec: 
      imagePullSecrets:
      - name: regcred
      containers:
        - name: hackathon-api
          image: europe-west3-docker.pkg.dev/cagip-hackathon-eq03-inno0-6b/hackathon/hackathon-api:dev
          imagePullPolicy: Always
          env:
            - name: VUE_APP_API_ENDPOINT
              value: 'http://<public_ip_hackathon-api>'
            - name: MONGOURI
              value: 'mongodb://mongo-0:27017/donation?retryWrites=true&w=majority'  
          livenessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /statistics
              scheme: HTTP
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hackathon-api-svc
  namespace: hackathon
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    app: hackathon-api
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: hackathon-api
